language: node_js
node_js:
  - "0.10"

sudo: true

branches:
  only:
    - master
before_script:
  - npm install -g bower
  - npm install -g gulp
  - npm install phantomjs
  - npm install -g karma
  - bower install
  - gulp scripts
  - gulp inject
  - gulp build
  - gulp test
  - sudo npm test
